version: '1.0'

SERVICES:
  app:
    build: ./app
  ports:
    - "8080:8080"
  depends_on:
    - db
  
  db:
    image:  postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_db
    volumes:
      - db_data:/var/lib/postgresql/data



volumes:
  db_data