services:
  avito_shop: 
    build: ./app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/merch_shop?sslmode=disable
    depends_on:
      - db
  
  db:
    image:  postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: merch_shop




